language: objective-c
osx_image: xcode8
compiler:
- clang
before_install:
- xcrun --show-sdk-path
- brew update
- command -v cmake >/dev/null 2>&1 || { brew install cmake; }
- scripts/./osx.sh
- export PATH="$(pwd)/llvm/bin":$PATH
- which llvm-config
- clang --version
script:
- cmake .
- make
- ls
#- ./yorkie < examples/fib.yk 2>&1 | clang -x ir -
#- ./a.out
sudo: true
